[package]
name = "torch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuten = { version = "0.1.0", git = "https://github.com/museun/shuten" }
